dataframe:
  - dask/dataframe/*
  - dask/dataframe/**/*

array:
  - dask/array/*
  - dask/array/**/*

io:
  - dask/dataframe/io/*
  - dask/dataframe/io/**/*

documentation:
  - docs/*
  - docs/**/*

dispatch:
  - dask/array/backends.py
  - dask/array/dispatch.py
  - dask/dataframe/backends.py
  - dask/dataframe/dispatch.py
  - dask/dataframe/extensions.py
