name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - packaging=20.0
  - python=3.8
  - pyyaml=5.3.1
  - click=7.0
  - cloudpickle=1.1.1
  - partd=1.2.0
  - fsspec=0.6.0
  - importlib-metadata=4.13.0
  - toolz=0.8.2
  # optional dependencies pulled in by pip install dask[array]
  - numpy=1.21
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-xdist
