# This job includes coverage
name: test-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  # required dependencies
  - python=3.11
  - packaging
  - pyyaml
  - click
  - cloudpickle
  - partd
  - fsspec
  - importlib_metadata
  - toolz
  # test dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
  - moto
  # Optional dependencies
  - mimesis
  - numpy
  - pandas
  - flask
  - fastparquet>=0.8.0
  - h5py
  - pytables
  - zarr
  # `tiledb-py=0.17.5` lead to strange seg faults in CI, However 0.18 is needed for 3.11
  # https://github.com/dask/dask/pull/9569
  # - tiledb-py # crashes on Python 3.11
  # - pyspark
  # - tiledb>=2.5.0 # crashes on Python 3.11
  - xarray
  # Pin until sqlalchemy 2 support is added https://github.com/dask/dask/issues/9896
  - sqlalchemy>=1.4.0,<2
  - pyarrow>=11
  - coverage
  - jsonschema
  # # other -- IO
  - boto3
  - botocore
  # Temporary restriction until https://github.com/dask/distributed/issues/7173 is resolved
  - bokeh
  - httpretty
  - aiohttp
  # # Need recent version of s3fs to support newer aiobotocore versions
  # # https://github.com/dask/s3fs/issues/514
  - s3fs>=2021.8.0
  # Need a new `crick` release with support for `numpy=1.24+`
  # https://github.com/dask/crick/issues/25
  # - crick
  - cytoolz
  - distributed
  - ipython
  - ipycytoscape
  # until https://github.com/jupyter-widgets/ipywidgets/issues/3731 is fixed
  - ipywidgets<8.0.5
  - ipykernel<6.22.0
  - lz4
  # https://github.com/numba/numba/issues/8304
  # - numba  # not supported on 3.11
  - psutil
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - python-snappy
  # - sparse  needs numba
  - cachey
  - python-graphviz
  - python-xxhash
  - mmh3
  - jinja2
  - pip
  - pip:
    - git+https://github.com/dask/distributed
